version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
    - WATCHPACK_POLLING=true    # ensure file changes are detected
    - HOST=0.0.0.0              # bind dev server to all interfaces

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/tx_metrics.db:/app/tx_metrics.db
      - ./server/index.js:/app/index.js
    #  - /app/node_modules
    #  - /app/iden3_repo/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true    # ensure file changes are detected
      - HOST=0.0.0.0              # bind dev server to all interfaces